env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
ignorePatterns:
  - build/*
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
